;;; remove paths
(delete "/usr/share/emacs/28.2/lisp/org" load-path)
(delete "/usr/share/emacs/28.3/lisp/org" load-path)
(delete "/usr/share/emacs/29.1/lisp/org" load-path)
(delete "/usr/share/emacs/29.4/lisp/org" load-path)
(delete "/usr/share/emacs/site-lisp" load-path)
(delete "/usr/share/emacs/site-lisp/SuperCollider" load-path)
(delete "/usr/share/emacs/site-lisp/acl2" load-path)
(delete "/usr/share/emacs/site-lisp/auctex" load-path)
(delete "/usr/share/emacs/site-lisp/autoconf" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format-13" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format-14" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format-15" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format-16" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format-17" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format-18" load-path)
(delete "/usr/share/emacs/site-lisp/clang-format-19" load-path)
(delete "/usr/share/emacs/site-lisp/cmake" load-path)
(delete "/usr/share/emacs/site-lisp/dictionaries-common" load-path)
(delete "/usr/share/emacs/site-lisp/ebuild-mode" load-path)
(delete "/usr/share/emacs/site-lisp/erlang" load-path)
(delete "/usr/share/emacs/site-lisp/eselect-mode" load-path)
(delete "/usr/share/emacs/site-lisp/ess" load-path)
(delete "/usr/share/emacs/site-lisp/gambc" load-path)
(delete "/usr/share/emacs/site-lisp/gcl" load-path)
(delete "/usr/share/emacs/site-lisp/gforth" load-path)
(delete "/usr/share/emacs/site-lisp/global" load-path)
(delete "/usr/share/emacs/site-lisp/gtypist" load-path)
(delete "/usr/share/emacs/site-lisp/latex-cjk-common" load-path)
(delete "/usr/share/emacs/site-lisp/latex-cjk-thai" load-path)
(delete "/usr/share/emacs/site-lisp/llvm" load-path)
(delete "/usr/share/emacs/site-lisp/llvm-13" load-path)
(delete "/usr/share/emacs/site-lisp/llvm-14" load-path)
(delete "/usr/share/emacs/site-lisp/llvm-15" load-path)
(delete "/usr/share/emacs/site-lisp/llvm-16" load-path)
(delete "/usr/share/emacs/site-lisp/llvm-17" load-path)
(delete "/usr/share/emacs/site-lisp/llvm-18" load-path)
(delete "/usr/share/emacs/site-lisp/llvm-19" load-path)
(delete "/usr/share/emacs/site-lisp/maxima" load-path)
(delete "/usr/share/emacs/site-lisp/mercury" load-path)
(delete "/usr/share/emacs/site-lisp/mmm-mode" load-path)
(delete "/usr/share/emacs/site-lisp/ninja" load-path)
(delete "/usr/share/emacs/site-lisp/po-mode" load-path)
(delete "/usr/share/emacs/site-lisp/proofgeneral" load-path)
(delete "/usr/share/emacs/site-lisp/rpm-spec-mode" load-path)
(delete "/usr/share/emacs/site-lisp/scheme48" load-path)
(delete "/usr/share/emacs/site-lisp/sdcc-ucsim" load-path)
(delete "/usr/share/emacs/site-lisp/systemtap-common" load-path)
(delete "/usr/share/emacs/site-lisp/verilog-mode" load-path)

;; debian
(delete "/etc/emacs/site-start.d" load-path)
(delete "/usr/share/emacs/site-lisp/elpa" load-path)
(delete "/usr/share/emacs/site-lisp/elpa/caml-4.9" load-path)
(delete "/usr/share/emacs/site-lisp/elpa/debian-el-37" load-path)
(delete "/usr/share/emacs/site-lisp/elpa/dpkg-dev-el-37.0" load-path)
(delete "/usr/share/emacs/site-lisp/elpa/ess-18.10.3snapshot" load-path)
(delete "/usr/share/emacs/site-lisp/elpa/notmuch-0.37" load-path)
(delete "/usr/share/emacs/site-lisp/elpa/rtags-2.38.130" load-path)
(delete "/usr/share/emacs/site-lisp/elpa-src" load-path)
(delete "/usr/share/emacs/site-lisp/elpa-src/caml-4.9" load-path)
(delete "/usr/share/emacs/site-lisp/elpa-src/debian-el-37" load-path)
(delete "/usr/share/emacs/site-lisp/elpa-src/dpkg-dev-el-37.0" load-path)
(delete "/usr/share/emacs/site-lisp/elpa-src/ess-18.10.3snapshot" load-path)
(delete "/usr/share/emacs/site-lisp/elpa-src/notmuch-0.37" load-path)
(delete "/usr/share/emacs/site-lisp/elpa-src/rtags-2.38.130" load-path)

;; gentoo
(delete "/usr/share/emacs/site-lisp/site-gentoo.d" load-path)

;;; add paths
(add-to-list 'load-path "/home/enomem/.rosws/noetic/share/emacs/site-lisp")

(provide 'enomem/en-loadpath)
