                             ;;;;;;;;;;;;;;;;;;;;;
                             ;;;  enomem mode  ;;;
                             ;;;;;;;;;;;;;;;;;;;;;

(use-package enomem/en :load-path "site-lisp" :defer t
  :init
  (defvar enomem-mode-map (make-keymap) "Key bindings for enomem-mode.")
  (define-minor-mode enomem-mode
    "enomem's minor mode" t " ~enomem" 'enomem-mode-map)
  (setq use-package-verbose 'debug)
  ;; enomem/en-keys
  (use-package enomem/en-keys :load-path "site-lisp")
  ;; enomem/en-loadpath
  (use-package enomem/en-loadpath :load-path "site-lisp")
  ;; enomem/en-scripts
  (use-package enomem/en-scripts :load-path "site-lisp")
  ;; enomem/en-settings
  (use-package enomem/en-settings :load-path "site-lisp")
  ;; enomem/en-style
  (use-package enomem/en-style :load-path "site-lisp")
  ;; enomem/en-emacs
  (use-package enomem/en-emacs :load-path "site-lisp")
  ;; system/system
  (use-package system/system :load-path "site-lisp"))

(use-package enomem/en-apps :load-path "site-lisp")
(use-package enomem/en-art :load-path "site-lisp")
(use-package enomem/en-asm :load-path "site-lisp")
(use-package enomem/en-browser :load-path "site-lisp")
(use-package enomem/en-build :load-path "site-lisp")
(use-package enomem/en-cedet :load-path "site-lisp")
(use-package enomem/en-c++ :load-path "site-lisp")
(use-package enomem/en-clojure :load-path "site-lisp")
(use-package enomem/en-comint :load-path "site-lisp")
(use-package enomem/en-company :load-path "site-lisp")
(use-package enomem/en-company-ansible :load-path "site-lisp")
(use-package enomem/en-company-build :load-path "site-lisp")
(use-package enomem/en-company-cedet :load-path "site-lisp")
(use-package enomem/en-company-c++ :load-path "site-lisp")
(use-package enomem/en-company-coq :load-path "site-lisp")
(use-package enomem/en-company-elisp :load-path "site-lisp")
(use-package enomem/en-company-gap :load-path "site-lisp")
(use-package enomem/en-company-go :load-path "site-lisp")
(use-package enomem/en-company-haskell :load-path "site-lisp")
(use-package enomem/en-company-java :load-path "site-lisp")
(use-package enomem/en-company-js :load-path "site-lisp")
(use-package enomem/en-company-ml :load-path "site-lisp")
(use-package enomem/en-company-python :load-path "site-lisp")
(use-package enomem/en-company-rust :load-path "site-lisp")
(use-package enomem/en-company-scheme :load-path "site-lisp")
(use-package enomem/en-company-shell :load-path "site-lisp")
(use-package enomem/en-conf :load-path "site-lisp")
(use-package enomem/en-crypt :load-path "site-lisp")
(use-package enomem/en-dap :load-path "site-lisp")
(use-package enomem/en-dap-c++ :load-path "site-lisp")
(use-package enomem/en-dap-go :load-path "site-lisp")
(use-package enomem/en-dap-java :load-path "site-lisp")
(use-package enomem/en-dap-python :load-path "site-lisp")
(use-package enomem/en-data :load-path "site-lisp")
(use-package enomem/en-db :load-path "site-lisp")
(use-package enomem/en-debug :load-path "site-lisp")
(use-package enomem/en-dev :load-path "site-lisp")
(use-package enomem/en-devops :load-path "site-lisp")
(use-package enomem/en-dict :load-path "site-lisp")
(use-package enomem/en-dired :load-path "site-lisp")
(use-package enomem/en-docker :load-path "site-lisp")
(use-package enomem/en-docs :load-path "site-lisp")
(use-package enomem/en-edit :load-path "site-lisp")
(use-package enomem/en-elisp :load-path "site-lisp")
(use-package enomem/en-emacs :load-path "site-lisp")
(use-package enomem/en-embedded :load-path "site-lisp")
(use-package enomem/en-erlang :load-path "site-lisp")
(use-package enomem/en-fly :load-path "site-lisp")
(use-package enomem/en-fly-c++ :load-path "site-lisp")
(use-package enomem/en-fly-cwl :load-path "site-lisp")
(use-package enomem/en-fly-haskell :load-path "site-lisp")
(use-package enomem/en-fly-java :load-path "site-lisp")
(use-package enomem/en-fly-rust :load-path "site-lisp")
(use-package enomem/en-fly-tcl :load-path "site-lisp")
(use-package enomem/en-fold :load-path "site-lisp")
(use-package enomem/en-forth :load-path "site-lisp")
(use-package enomem/en-gl :load-path "site-lisp")
(use-package enomem/en-go :load-path "site-lisp")
(use-package enomem/en-graphics :load-path "site-lisp")
(use-package enomem/en-haskell :load-path "site-lisp")
(use-package enomem/en-java :load-path "site-lisp")
(use-package enomem/en-js :load-path "site-lisp")
(use-package enomem/en-jupyter :load-path "site-lisp")
(use-package enomem/en-keys :load-path "site-lisp")
(use-package enomem/en-ledger :load-path "site-lisp")
(use-package enomem/en-linux :load-path "site-lisp")
(use-package enomem/en-lisp :load-path "site-lisp")
(use-package enomem/en-loadpath :load-path "site-lisp")
(use-package enomem/en-lsp :load-path "site-lisp")
(use-package enomem/en-lsp-asy :load-path "site-lisp")
(use-package enomem/en-lsp-c++ :load-path "site-lisp")
(use-package enomem/en-lsp-clojure :load-path "site-lisp")
(use-package enomem/en-lsp-cwl :load-path "site-lisp")
(use-package enomem/en-lsp-go :load-path "site-lisp")
(use-package enomem/en-lsp-haskell :load-path "site-lisp")
(use-package enomem/en-lsp-java :load-path "site-lisp")
(use-package enomem/en-lsp-js :load-path "site-lisp")
(use-package enomem/en-lsp-json :load-path "site-lisp")
(use-package enomem/en-lsp-jsonnet :load-path "site-lisp")
(use-package enomem/en-lsp-lua :load-path "site-lisp")
(use-package enomem/en-lsp-org :load-path "site-lisp")
(use-package enomem/en-lsp-perl :load-path "site-lisp")
(use-package enomem/en-lsp-python :load-path "site-lisp")
(use-package enomem/en-lsp-ruby :load-path "site-lisp")
(use-package enomem/en-lsp-rust :load-path "site-lisp")
(use-package enomem/en-lsp-shell :load-path "site-lisp")
(use-package enomem/en-lsp-vala :load-path "site-lisp")
(use-package enomem/en-lsp-xml :load-path "site-lisp")
(use-package enomem/en-lsp-yaml :load-path "site-lisp")
(use-package enomem/en-lua :load-path "site-lisp")
(use-package enomem/en-mail :load-path "site-lisp")
(use-package enomem/en-math :load-path "site-lisp")
(use-package enomem/en-ml :load-path "site-lisp")
(use-package enomem/en-mode :load-path "site-lisp")
(use-package enomem/en-net :load-path "site-lisp")
(use-package enomem/en-org :load-path "site-lisp")
(use-package enomem/en-perl :load-path "site-lisp")
(use-package enomem/en-prog :load-path "site-lisp")
(use-package enomem/en-prolog :load-path "site-lisp")
(use-package enomem/en-proof :load-path "site-lisp")
(use-package enomem/en-python :load-path "site-lisp")
(use-package enomem/en-qt :load-path "site-lisp")
(use-package enomem/en-r :load-path "site-lisp")
(use-package enomem/en-rev :load-path "site-lisp")
(use-package enomem/en-ros :load-path "site-lisp")
(use-package enomem/en-ruby :load-path "site-lisp")
(use-package enomem/en-rust :load-path "site-lisp")
(use-package enomem/en-scheme :load-path "site-lisp")
(use-package enomem/en-scripts :load-path "site-lisp")
(use-package enomem/en-settings :load-path "site-lisp")
(use-package enomem/en-shell :load-path "site-lisp")
(use-package enomem/en-spell :load-path "site-lisp")
(use-package enomem/en-style :load-path "site-lisp")
(use-package enomem/en-tags :load-path "site-lisp")
(use-package enomem/en-tcl :load-path "site-lisp")
(use-package enomem/en-test :load-path "site-lisp")
(use-package enomem/en-tex :load-path "site-lisp")
(use-package enomem/en-text :load-path "site-lisp")
(use-package enomem/en-vala :load-path "site-lisp")
(use-package enomem/en-vc :load-path "site-lisp")
(use-package enomem/en-web :load-path "site-lisp")
(use-package enomem/en-xml :load-path "site-lisp")
(use-package enomem/en-yas :load-path "site-lisp")


(provide 'enomem/en)
