;;; devdocs-lookup.el --- jump to documentation on devdocs.io -*- lexical-binding: t; -*-

;; This is free and unencumbered software released into the public domain.

;; Author: Christopher Wellons <wellons@nullprogram.com>
;; URL: https://github.com/skeeto/devdocs-lookup

;;; Commentary:

;; This package provides an interactive function `devdocs-lookup' to
;; quickly jump to documentation on a particular API at devdocs.io
;; with your browser.

;; https://devdocs.io/

;; Currently supported subjects:

;; Angular.js, Apache HTTP Server, Backbone.js, Bower, C, Chai,
;; Clojure, CoffeeScript, Cordova, C++, CSS, D3.js, Django, Dojo, DOM,
;; DOM Events, Drupal, Elixir, Ember.js, Express, Flow, Git, Go,
;; Grunt, Haskell, HTML, HTTP, io.js, JavaScript, jQuery, jQuery
;; Mobile, jQuery UI, Knockout.js, Laravel, Less, lodash, Lua,
;; Marionette.js, Markdown, Meteor, Ruby / Minitest, mocha, Modernizr,
;; Moment.js, Mongoose, nginx, Node.js, Node.js (LTS), Nokogiri, npm,
;; OpenTSDB, Phalcon, Phaser, Phoenix, PHP, PHPUnit, PostgreSQL,
;; Python, Q, Ruby on Rails, React, React Native, Redis, Relay,
;; RequireJS, RethinkDB, Ruby, Rust, Sass, Sinon, Socket.IO, SVG,
;; Symfony, Underscore.js, Vagrant, Vue.js, webpack, XPath, Yii.

;; To bypass indicating the subject on each lookup, devdocs-lookup can
;; generate interactive commands for each of the individual subjects
;; by calling `devdocs-setup'.

;; (devdocs-setup)
;; (global-set-key (kbd "C-h C-c") #'devdocs-lookup-c)
;; (global-set-key (kbd "C-h C-p") #'devdocs-lookup-python)

;;; Code:

(require 'url)
(require 'json)
(require 'cl-lib)

(defvar devdocs-base-url "https://devdocs.io"
  "Base url for devdocs.io.")

(defvar devdocs-base-index-url "https://docs.devdocs.io"
  "Base url for devdocs.io.")

(defvar devdocs-subjects
  '(("angular" "angular")
    ("angular~16" "angular~16")
    ("angular~5" "angular~5")
    ("angular~4" "angular~4")
    ("angular~2" "angular~2")
    ("angularjs~1.8" "angularjs~1.8")
    ("ansible" "ansible")
    ("ansible~2.11" "ansible~2.11")
    ("apache_http_server" "apache_http_server")
    ("apache_pig~0.17" "apache_pig~0.17")
    ("astro" "astro")
    ("async" "async")
    ("axios" "axios")
    ("babel~7" "babel~7")
    ("babel~6" "babel~6")
    ("backbone" "backbone")
    ("bash" "bash")
    ("bazel~7.0" "bazel~7.0")
    ("bazel~6.0" "bazel~6.0")
    ("bluebird" "bluebird")
    ("bootstrap~5" "bootstrap~5")
    ("bootstrap~4" "bootstrap~4")
    ("bootstrap~3" "bootstrap~3")
    ("bottle~0.12" "bottle~0.12")
    ("bower" "bower")
    ("c" "c")
    ("cpp" "cpp")
    ("cakephp~4.4" "cakephp~4.4")
    ("chai" "chai")
    ("chef~18" "chef~18")
    ("chef~11" "chef~11")
    ("clojure~1.11" "clojure~1.11")
    ("clojure~1.7" "clojure~1.7")
    ("cmake~3.26" "cmake~3.26")
    ("cmake~3.5" "cmake~3.5")
    ("codeception" "codeception")
    ("codeceptjs" "codeceptjs")
    ("codeigniter~4" "codeigniter~4")
    ("codeigniter~3" "codeigniter~3")
    ("coffeescript~2" "coffeescript~2")
    ("coffeescript~1" "coffeescript~1")
    ("composer" "composer")
    ("cordova~9" "cordova~9")
    ("cordova~6" "cordova~6")
    ("crystal" "crystal")
    ("css" "css")
    ("cypress" "cypress")
    ("d" "d")
    ("d3~7" "d3~7")
    ("d3~3" "d3~3")
    ("dart~2" "dart~2")
    ("dart~1" "dart~1")
    ("date_fns" "date_fns")
    ("deno" "deno")
    ("django~4.2" "django~4.2")
    ("django~3.2" "django~3.2")
    ("django~2.2" "django~2.2")
    ("django~1.8" "django~1.8")
    ("django_rest_framework" "django_rest_framework")
    ("docker" "docker")
    ("docker~19" "docker~19")
    ("docker~1.13" "docker~1.13")
    ("dojo" "dojo")
    ("drupal~8" "drupal~8")
    ("drupal~7" "drupal~7")
    ("eigen3" "eigen3")
    ("electron" "electron")
    ("elisp" "elisp")
    ("elixir~1.15" "elixir~1.15")
    ("elixir~1.3" "elixir~1.3")
    ("ember~4" "ember~4")
    ("ember~3" "ember~3")
    ("ember~2" "ember~2")
    ("enzyme" "enzyme")
    ("erlang~26" "erlang~26")
    ("erlang~18" "erlang~18")
    ("esbuild" "esbuild")
    ("eslint" "eslint")
    ("express" "express")
    ("falcon~2.0" "falcon~2.0")
    ("falcon~1.4" "falcon~1.4")
    ("fastapi" "fastapi")
    ("fish~3.7" "fish~3.7")
    ("fish~2.7" "fish~2.7")
    ("flask~3.0" "flask~3.0")
    ("flask~2.3" "flask~2.3")
    ("flask~1.1" "flask~1.1")
    ("flask~0.12" "flask~0.12")
    ("flow" "flow")
    ("fluture" "fluture")
    ("gcc~13" "gcc~13")
    ("gcc~13_cpp" "gcc~13_cpp")
    ("gcc~12" "gcc~12")
    ("gcc~12_cpp" "gcc~12_cpp")
    ("gcc~11" "gcc~11")
    ("gcc~11_cpp" "gcc~11_cpp")
    ("gcc~10" "gcc~10")
    ("gcc~10_cpp" "gcc~10_cpp")
    ("gcc~9" "gcc~9")
    ("gcc~9_cpp" "gcc~9_cpp")
    ("gcc~8" "gcc~8")
    ("gcc~8_cpp" "gcc~8_cpp")
    ("gcc~7" "gcc~7")
    ("gcc~7_cpp" "gcc~7_cpp")
    ("gcc~6" "gcc~6")
    ("gcc~6_cpp" "gcc~6_cpp")
    ("gcc~5" "gcc~5")
    ("gcc~5_cpp" "gcc~5_cpp")
    ("gcc~4" "gcc~4")
    ("gcc~4_cpp" "gcc~4_cpp")
    ("git" "git")
    ("gnu_fortran~13" "gnu_fortran~13")
    ("gnu_fortran~4" "gnu_fortran~4")
    ("gnu_make" "gnu_make")
    ("gnu_cobol" "gnu_cobol")
    ("gnuplot" "gnuplot")
    ("go" "go")
    ("godot~3.5" "godot~3.5")
    ("godot~2.1" "godot~2.1")
    ("graphite" "graphite")
    ("groovy~4.0" "groovy~4.0")
    ("groovy~3.0" "groovy~3.0")
    ("groovy~2.5" "groovy~2.5")
    ("grunt" "grunt")
    ("gtk~4.0" "gtk~4.0")
    ("gtk~3.24" "gtk~3.24")
    ("handlebars" "handlebars")
    ("hapi" "hapi")
    ("haproxy~2.8" "haproxy~2.8")
    ("haproxy~1.9" "haproxy~1.9")
    ("haskell~9" "haskell~9")
    ("haskell~8" "haskell~8")
    ("haskell~7" "haskell~7")
    ("haxe" "haxe")
    ("haxe~cpp" "haxe~cpp")
    ("haxe~cs" "haxe~cs")
    ("haxe~flash" "haxe~flash")
    ("haxe~java" "haxe~java")
    ("haxe~javascript" "haxe~javascript")
    ("haxe~neko" "haxe~neko")
    ("haxe~php" "haxe~php")
    ("haxe~lua" "haxe~lua")
    ("haxe~hashlink" "haxe~hashlink")
    ("haxe~sys" "haxe~sys")
    ("haxe~python" "haxe~python")
    ("haxe~eval" "haxe~eval")
    ("homebrew" "homebrew")
    ("html" "html")
    ("http" "http")
    ("i3" "i3")
    ("immutable" "immutable")
    ("influxdata" "influxdata")
    ("jasmine" "jasmine")
    ("javascript" "javascript")
    ("jekyll~4" "jekyll~4")
    ("jekyll~3" "jekyll~3")
    ("jest" "jest")
    ("jinja~3.1" "jinja~3.1")
    ("jinja~2.11" "jinja~2.11")
    ("joi" "joi")
    ("jq" "jq")
    ("jquery" "jquery")
    ("jquerymobile" "jquerymobile")
    ("jqueryui" "jqueryui")
    ("jsdoc" "jsdoc")
    ("julia~1.10" "julia~1.10")
    ("julia~0.7" "julia~0.7")
    ("knockout" "knockout")
    ("koa" "koa")
    ("kotlin~1.9" "kotlin~1.9")
    ("kubectl" "kubectl")
    ("kubectl~1.20" "kubectl~1.20")
    ("kubernetes" "kubernetes")
    ("kubernetes~1.20" "kubernetes~1.20")
    ("laravel~10" "laravel~10")
    ("laravel~5.8" "laravel~5.8")
    ("laravel~4.2" "laravel~4.2")
    ("latex" "latex")
    ("leaflet~1.9" "leaflet~1.9")
    ("less~4" "less~4")
    ("less~3" "less~3")
    ("less~2" "less~2")
    ("liquid" "liquid")
    ("lodash~4" "lodash~4")
    ("lodash~3" "lodash~3")
    ("lodash~2" "lodash~2")
    ("lua~5.4" "lua~5.4")
    ("lua~5.3" "lua~5.3")
    ("lua~5.2" "lua~5.2")
    ("lua~5.1" "lua~5.1")
    ("love" "love")
    ("mariadb" "mariadb")
    ("marionette~4" "marionette~4")
    ("marionette~3" "marionette~3")
    ("marionette~2" "marionette~2")
    ("markdown" "markdown")
    ("matplotlib~3.7" "matplotlib~3.7")
    ("matplotlib~2.2" "matplotlib~2.2")
    ("matplotlib~1.5" "matplotlib~1.5")
    ("meteor~1.5" "meteor~1.5")
    ("mocha" "mocha")
    ("modernizr" "modernizr")
    ("moment" "moment")
    ("moment_timezone" "moment_timezone")
    ("mongoose" "mongoose")
    ("nginx" "nginx")
    ("nginx_lua_module" "nginx_lua_module")
    ("nim" "nim")
    ("nix" "nix")
    ("node" "node")
    ("node~18_lts" "node~18_lts")
    ("node~16_lts" "node~16_lts")
    ("node~14_lts" "node~14_lts")
    ("node~12_lts" "node~12_lts")
    ("node~10_lts" "node~10_lts")
    ("node~8_lts" "node~8_lts")
    ("node~6_lts" "node~6_lts")
    ("node~4_lts" "node~4_lts")
    ("nokogiri" "nokogiri")
    ("npm" "npm")
    ("numpy~1.23" "numpy~1.23")
    ("numpy~1.17" "numpy~1.17")
    ("numpy~1.10" "numpy~1.10")
    ("nushell" "nushell")
    ("ocaml" "ocaml")
    ("ocaml~4.14" "ocaml~4.14")
    ("octave~8" "octave~8")
    ("octave~7" "octave~7")
    ("octave~6" "octave~6")
    ("octave~5" "octave~5")
    ("openjdk~21" "openjdk~21")
    ("openjdk~17" "openjdk~17")
    ("openjdk~11" "openjdk~11")
    ("openjdk~8" "openjdk~8")
    ("openjdk~8_gui" "openjdk~8_gui")
    ("openjdk~8_web" "openjdk~8_web")
    ("opentsdb" "opentsdb")
    ("padrino" "padrino")
    ("pandas~1" "pandas~1")
    ("pandas~0.25" "pandas~0.25")
    ("perl~5.38" "perl~5.38")
    ("perl~5.28" "perl~5.28")
    ("perl~5.26" "perl~5.26")
    ("phalcon~3" "phalcon~3")
    ("phalcon~2" "phalcon~2")
    ("phaser" "phaser")
    ("phoenix" "phoenix")
    ("php" "php")
    ("phpunit~9" "phpunit~9")
    ("phpunit~4" "phpunit~4")
    ("point_cloud_library" "point_cloud_library")
    ("pony" "pony")
    ("postgresql~16" "postgresql~16")
    ("postgresql~15" "postgresql~15")
    ("postgresql~14" "postgresql~14")
    ("postgresql~13" "postgresql~13")
    ("postgresql~12" "postgresql~12")
    ("postgresql~11" "postgresql~11")
    ("postgresql~10" "postgresql~10")
    ("postgresql~9.6" "postgresql~9.6")
    ("prettier" "prettier")
    ("pug" "pug")
    ("puppeteer" "puppeteer")
    ("pygame" "pygame")
    ("python~3.12" "python~3.12")
    ("python~3.11" "python~3.11")
    ("python~3.10" "python~3.10")
    ("python~3.9" "python~3.9")
    ("python~3.8" "python~3.8")
    ("python~3.7" "python~3.7")
    ("python~3.6" "python~3.6")
    ("python~3.5" "python~3.5")
    ("python~2.7" "python~2.7")
    ("pytorch" "pytorch")
    ("q" "q")
    ("qt" "qt")
    ("qt~6.1" "qt~6.1")
    ("qt~5.15" "qt~5.15")
    ("qt~5.11" "qt~5.11")
    ("qt~5.9" "qt~5.9")
    ("qt~5.6" "qt~5.6")
    ("qunit" "qunit")
    ("r" "r")
    ("ramda" "ramda")
    ("react" "react")
    ("react_bootstrap" "react_bootstrap")
    ("react_native" "react_native")
    ("react_router" "react_router")
    ("reactivex" "reactivex")
    ("redis" "redis")
    ("redux" "redux")
    ("redux~3" "redux~3")
    ("relay~10" "relay~10")
    ("relay~9" "relay~9")
    ("relay~8" "relay~8")
    ("requests" "requests")
    ("requirejs" "requirejs")
    ("rethinkdb~javascript" "rethinkdb~javascript")
    ("rethinkdb~ruby" "rethinkdb~ruby")
    ("rethinkdb~python" "rethinkdb~python")
    ("rethinkdb~java" "rethinkdb~java")
    ("ruby~3.3" "ruby~3.3")
    ("ruby~3.2" "ruby~3.2")
    ("ruby~3.1" "ruby~3.1")
    ("ruby~3" "ruby~3")
    ("ruby~2.7" "ruby~2.7")
    ("ruby~2.6" "ruby~2.6")
    ("minitest" "minitest")
    ("rails~7.1" "rails~7.1")
    ("rails~6.1" "rails~6.1")
    ("rails~5.2" "rails~5.2")
    ("rails~4.2" "rails~4.2")
    ("rust" "rust")
    ("rxjs" "rxjs")
    ("saltstack" "saltstack")
    ("sanctuary" "sanctuary")
    ("sanctuary_def" "sanctuary_def")
    ("sanctuary_type_classes" "sanctuary_type_classes")
    ("sass" "sass")
    ("scala~3.2" "scala~3.2")
    ("scala~3.1" "scala~3.1")
    ("scala~2.13_library" "scala~2.13_library")
    ("scala~2.13_reflection" "scala~2.13_reflection")
    ("scikit_image" "scikit_image")
    ("scikit_learn" "scikit_learn")
    ("sequelize~6" "sequelize~6")
    ("sinon~15" "sinon~15")
    ("sinon~1" "sinon~1")
    ("socketio~4" "socketio~4")
    ("socketio~3" "socketio~3")
    ("socketio~2" "socketio~2")
    ("spring_boot" "spring_boot")
    ("sqlite" "sqlite")
    ("statsmodels" "statsmodels")
    ("browser_support_tables" "browser_support_tables")
    ("svelte" "svelte")
    ("svelte~3" "svelte~3")
    ("svg" "svg")
    ("symfony~4.1" "symfony~4.1")
    ("symfony~3.4" "symfony~3.4")
    ("symfony~2.8" "symfony~2.8")
    ("tailwindcss" "tailwindcss")
    ("tcl_tk" "tcl_tk")
    ("tensorflow~2.9" "tensorflow~2.9")
    ("tensorflow~1.15" "tensorflow~1.15")
    ("tensorflow_cpp~2.9" "tensorflow_cpp~2.9")
    ("tensorflow_cpp~1.15" "tensorflow_cpp~1.15")
    ("terraform" "terraform")
    ("trio" "trio")
    ("twig~3" "twig~3")
    ("twig~2" "twig~2")
    ("twig~1" "twig~1")
    ("typescript" "typescript")
    ("typescript~5.1" "typescript~5.1")
    ("underscore" "underscore")
    ("vagrant" "vagrant")
    ("varnish" "varnish")
    ("vite" "vite")
    ("vite~4" "vite~4")
    ("vite~3" "vite~3")
    ("vitest" "vitest")
    ("vue~3" "vue~3")
    ("vue~2" "vue~2")
    ("vue~1" "vue~1")
    ("vue_router~4" "vue_router~4")
    ("vue_router~3" "vue_router~3")
    ("vueuse" "vueuse")
    ("vuex~4" "vuex~4")
    ("vuex~3" "vuex~3")
    ("vulkan" "vulkan")
    ("wagtail" "wagtail")
    ("wagtail~3" "wagtail~3")
    ("wagtail~2" "wagtail~2")
    ("dom" "dom")
    ("web_extensions" "web_extensions")
    ("webpack~5" "webpack~5")
    ("webpack~4" "webpack~4")
    ("webpack~1" "webpack~1")
    ("werkzeug~3.0" "werkzeug~3.0")
    ("werkzeug~2.3" "werkzeug~2.3")
    ("werkzeug~1.0" "werkzeug~1.0")
    ("werkzeug~0.16" "werkzeug~0.16")
    ("wordpress" "wordpress")
    ("xslt_xpath" "xslt_xpath")
    ("yarn~berry" "yarn~berry")
    ("yarn~classic" "yarn~classic")
    ("yii~2.0" "yii~2.0")
    ("yii~1.1" "yii~1.1")
    ("zig" "zig"))
  "List of subjects supported by devdocs.io.")

(defvar-local devdocs--default-subject nil
  "Remembers the subject for the given buffer.")

(defvar devdocs-index (make-hash-table :test 'equal)
  "Hash table for indexes for various subjects.")

(defun devdocs-index (subject &optional callback)
  "Return the devdocs.io index for SUBJECT, optionally async via CALLBACK."
  (cl-declare (special url-http-end-of-headers))
  (let ((index (gethash subject devdocs-index))
        (url (format "%s/%s/index.json" devdocs-base-index-url subject)))
    (cond ((and index callback)
           (funcall callback index))
          ((and index (not callback))
           index)
          ((and (not index) (not callback))
           (with-current-buffer (url-retrieve-synchronously url nil t)
             (goto-char url-http-end-of-headers)
             (setf (gethash subject devdocs-index) (json-read))))
          ((and (not index) callback)
           (url-retrieve
            url
            (lambda (_)
              (goto-char url-http-end-of-headers)
              (setf (gethash subject devdocs-index) (json-read))
              (funcall callback (gethash subject devdocs-index))))))))

(defun devdocs-entries (subject)
  "Return an association list of the entries in SUBJECT."
  (cl-loop for entry across (cdr (assoc 'entries (devdocs-index subject)))
           collect (cons (cdr (assoc 'name entry))
                         (cdr (assoc 'path entry)))))

(defvar devdoc--hist-subjects nil)

(defun devdocs-read-subject ()
  "Interactively ask the user for a subject."
  (let* ((subjects (mapcar #'car devdocs-subjects))
         (hist 'devdoc--hist-subjects)
         (subject (completing-read "Subject: " subjects nil t nil hist)))
    (cadr (assoc subject devdocs-subjects))))

(defun devdocs--best-match (string names)
  "Return the best match for STRING in NAMES, if any.
An exact match takes the highest priority, then a partial match
on symbol boundaries, then any partial match. Matches are
case-sensitive."
  (let* ((best-match nil)
         (best-score 0)
         (case-fold-search nil)
         (re-float (regexp-quote string))
         (re-symbol (concat "\\_<" re-float "\\_>")))
    (dolist (name names)
      (cond
       ;; Exact match
       ((and (< best-score 100)
             (string= string name))
        (setf best-match name
              best-score 100))
       ;; Symbol-boundary match
       ((and (< best-score 80)
             (string-match-p re-symbol name))
        (setf best-match name
              best-score 80))
       ;; Loose match
       ((and (< best-score 60)
             (let ((case-fold-search t))
               (string-match-p re-float name)))
        (setf best-match name
              best-score 60))))
    best-match))

(defun devdocs-read-entry (subject)
  "Interactively ask the user for an entry in SUBJECT."
  (let* ((names (mapcar #'car (devdocs-entries subject)))
         (hist (intern (format "devdocs--hist-%s" subject)))
         (symbol (symbol-at-point))
         (best-match
          (and symbol (devdocs--best-match (symbol-name symbol) names)))
         (prompt (if best-match
                     (format "Entry (%s) [%s]: " best-match subject)
                   (format "Entry [%s]: " subject))))
    (completing-read prompt names nil :require-match nil hist best-match)))

;;;###autoload
(defun devdocs-lookup (subject entry)
  "Visit the documentation for ENTRY from SUBJECT in a browser."
  (interactive
   ;; Try to guess the subject from the major mode.
   (let* ((case-fold-search t)
          (major-mode-string
           (replace-regexp-in-string "-mode$" "" (symbol-name major-mode)))
          (subject-dwim (cadr (cl-assoc major-mode-string devdocs-subjects
                                        :test #'string-match-p)))
          (subject (if current-prefix-arg
                       (devdocs-read-subject)
                     (or devdocs--default-subject
                         subject-dwim
                         (devdocs-read-subject))))
          (entry (devdocs-read-entry subject)))
     (when subject
       (setf devdocs--default-subject subject))
     (list subject entry)))
  (let ((path (cdr (assoc entry (devdocs-entries subject)))))
    (when path
      (setq browse-url-browser-function 'browse-url-firefox)
      (browse-url (format "%s/%s/%s" devdocs-base-url subject path))
      :found)))

;;;###autoload
(defun devdocs-setup ()
  "Generate an interactive command for each subject (`devdocs-subjects')."
  (dolist (pair devdocs-subjects)
    (cl-destructuring-bind (name subject) pair
      (let ((symbol (intern (format "devdocs-lookup-%s" subject))))
        (defalias symbol
          (lambda ()
            (interactive)
            (devdocs-lookup subject (devdocs-read-entry subject)))
          (format "Look up documentation for %s on devdocs.io." name))))))

(provide 'devdocs-lookup)

;;; devdocs-lookup.el ends here
